owner: chatwoot
repo: status

sites:
  - name: Chatwoot
    url: https://app.chatwoot.com
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/chatwoot/status/master/assets/favicon.ico
  - name: Chatwoot Hub
    url: https://hub.2.chatwoot.com
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/chatwoot/status/master/assets/favicon.ico
assignees:
  - vishnu-narayanan
  - sojan-official
status-website:
  cname: status.chatwoot.com
  logoUrl: https://raw.githubusercontent.com/chatwoot/status/master/assets/chatwoot-icon.png
  favicon: https://raw.githubusercontent.com/chatwoot/status/master/assets/favicon.ico
  name: Chatwoot Status
  introTitle: "About this site"
  introMessage: Welcome to Chatwoot's real-time and historical data on system performance.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.gg/cJXdrwS
